name: 02-workflow-events

on: 
    push:
    pull_request:
    schedule:
        - cron: '*/5 * * * *'
    workflow_dispatch:

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Echo a message
              run: echo "I have been triggered by the event ${{ github.event_name }}."