name: 04-Using-Workflows

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install Dependencies Needed
        run: npm ci
        working-directory: ./.github/workflows/04-Using-Workflows/react-app