name: 06-contexts
run-name: 06-context | DEBUG - ${{ inputs.debug }}

on: 
    push:
    workflow_dispatch:
       inputs:
          debug:
            type: boolean
            default: false

jobs:
    echo-data:
        runs-on: ubuntu-latest
        steps:
            - name: Display Information
              run: |
                echo "GITHUB_EVENTNAME: ${{ github.event_name }}"
                echo "GITHUB_REF: ${{ github.ref }}"
                echo "GITHUB_SHA: ${{ github.sha }}"
                echo "GITHUB_ACTOR: ${{ github.actor }}"
                echo "GITHUB_WORKFLOW: ${{ github.workflow }}"
                echo "GITHUB_RUN ID: ${{ github.run_id }}"
                echo "GITHUB_RUN NUMBER: ${{ github.run_number }}"
            - name: Retrieve Variables
              run: |
                    echo "Variable : ${{ vars.MY_VARIABLE }}"