name: 07-expressions

on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: '[debug] print start-up data'
        if: ${{ github.event.inputs.debug == 'true' }}
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          echo "runner: ${{ runner.os }}"

      - name: '[debug] when start from main branch'
        if: ${{ github.event.inputs.debug == 'true' && github.ref == 'refs/heads/main' }}
        run: |
          echo "This run is triggered from main branch"

      - name: Greeting
        run: echo "Hello, World!"
